import { useEffect, useMemo, useState } from "react";
import AdminShell from "../../components/admin/AdminShell";
import PageLoader from "../../components/common/PageLoader";
import { getAllOrders } from "../../services/adminOrders";
function isSameDay(date){const now=new Date();const d=new Date(date);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()&&d.getDate()===now.getDate();}
function isWithinDays(date,days){const now=new Date();const d=new Date(date);return now-d<=days*24*60*60*1000;}
export default function AdminReportsPage(){const[loading,setLoading]=useState(true),[orders,setOrders]=useState([]),[error,setError]=useState("");
useEffect(()=>{(async()=>{setLoading(true);setError("");try{setOrders(await getAllOrders());}catch(err){setError(err.message||"تعذر تحميل التقارير");}finally{setLoading(false);}})();},[]);
const report=useMemo(()=>{const todayOrders=orders.filter((o)=>o.created_at&&isSameDay(o.created_at));const weekOrders=orders.filter((o)=>o.created_at&&isWithinDays(o.created_at,7));const monthOrders=orders.filter((o)=>o.created_at&&isWithinDays(o.created_at,30));const totalToday=todayOrders.reduce((s,o)=>s+Number(o.total_amount||0),0);const totalWeek=weekOrders.reduce((s,o)=>s+Number(o.total_amount||0),0);const totalMonth=monthOrders.reduce((s,o)=>s+Number(o.total_amount||0),0);const paymentMethodMap={},deliveryTypeMap={},productMap={};orders.forEach((order)=>{paymentMethodMap[order.payment_method||"unknown"]=(paymentMethodMap[order.payment_method||"unknown"]||0)+1;deliveryTypeMap[order.delivery_type||"unknown"]=(deliveryTypeMap[order.delivery_type||"unknown"]||0)+1;(order.order_items||[]).forEach((item)=>{productMap[item.product_name||"بدون اسم"]=(productMap[item.product_name||"بدون اسم"]||0)+Number(item.quantity||0);});});return{totalToday,totalWeek,totalMonth,topPaymentMethods:Object.entries(paymentMethodMap).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),topDeliveryTypes:Object.entries(deliveryTypeMap).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),topProducts:Object.entries(productMap).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count).slice(0,10)};},[orders]);
if(loading) return <AdminShell title="التقارير" subtitle="جاري تحميل التقارير"><PageLoader text="جاري تحميل التقارير" /></AdminShell>;
return <AdminShell title="التقارير" subtitle="نظرة تحليلية على المبيعات والطلبات">{error?<div className="error-box">{error}</div>:null}<div className="stats-grid"><div className="stat-card"><span>مبيعات اليوم</span><strong>{report.totalToday} ج</strong></div><div className="stat-card"><span>مبيعات آخر 7 أيام</span><strong>{report.totalWeek} ج</strong></div><div className="stat-card"><span>مبيعات آخر 30 يوم</span><strong>{report.totalMonth} ج</strong></div></div><div className="reports-grid"><div className="admin-card"><h2>أكثر طرق الدفع استخدامًا</h2>{report.topPaymentMethods.length===0?<p>لا توجد بيانات</p>:report.topPaymentMethods.map((item,index)=><p key={index}>{item.name} - {item.count} طلب</p>)}</div><div className="admin-card"><h2>أنواع الطلبات</h2>{report.topDeliveryTypes.length===0?<p>لا توجد بيانات</p>:report.topDeliveryTypes.map((item,index)=><p key={index}>{item.name==="delivery"?"دليفري":item.name==="pickup"?"استلام":item.name} - {item.count}</p>)}</div></div><div className="admin-card"><h2>أفضل المنتجات طلبًا</h2><div className="table-wrap"><table className="admin-table"><thead><tr><th>الترتيب</th><th>اسم المنتج</th><th>عدد القطع المطلوبة</th></tr></thead><tbody>{report.topProducts.map((item,index)=><tr key={item.name}><td>{index+1}</td><td>{item.name}</td><td>{item.count}</td></tr>)}{report.topProducts.length===0?<tr><td colSpan="3" style={{textAlign:"center",padding:"20px"}}>لا توجد بيانات</td></tr>:null}</tbody></table></div></div></AdminShell>; }